import type { Metadata } from "next";
import './globals.css'

export const metadata: Metadata = {
  title: {
    default:'about aryan',
    template:'%s | AryanSharma'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <header style={{ backgroundColor: "#baebf5", height: "5rem" }}>
          <p>header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: "#baebf5", height: "5rem" }}>
          <p>footer</p>
        </footer>
      </body>
    </html>
  );
}
